
// This file is generated by tools/generate-repo-ids.ts
// Do not edit this file directly

export const RepoIds = {
	BAKI: "MDEwOlJlcG9zaXRvcnkzNzkxMDE2OTM=",
	BAKI_GUI: "R_kgDOGU_rig",
	CHATTING_APP: "MDEwOlJlcG9zaXRvcnkyOTkyNTQwMDk=",
	CRICKET_TOURNAMENT_MANAGER: "MDEwOlJlcG9zaXRvcnkyNzIyMjYwNzY=",
	CRICVIZ: "R_kgDOHF6w5w",
	ECOMMERCE_SITE: "MDEwOlJlcG9zaXRvcnkyODYwNDUxNTU=",
	ECOMMERCE_SITE_BACKEND: "MDEwOlJlcG9zaXRvcnkyOTIzMjU4MjM=",
	MINIGREP: "R_kgDOGvNv0A",
	NFT_STAKING: "R_kgDOIYqadg",
	OSSU: "R_kgDOJlTWDQ",
	PORTFOLIO: "R_kgDOHA3WOA",
	REACT_COMPONENTS: "MDEwOlJlcG9zaXRvcnkzODMzNDE3OTg=",
	REMOTION_EXPERIMENT: "R_kgDOJotlxQ",
	RETOMIZER: "R_kgDOG9Bj9w",
	RUST_BOOTCAMP: "R_kgDOKLi3TA",
	SCORE_MAN: "MDEwOlJlcG9zaXRvcnkyODMzNjk3NTc=",
	SOLANA_MEMORY_ISSUE: "R_kgDOKQ-nOg",
	SONKET: "R_kgDOGfi9Vw",
	WWV_NFT_STAKING: "R_kgDOIYqZUQ"
}