
// This file is generated by tools/generate-repo-ids.ts
// Do not edit this file directly

export const RepoIds = {
	DEVFINDER: "R_kgDOMh0vig",
	PORTFOLIO: "R_kgDOHA3WOA",
	RETOMIZER: "R_kgDOG9Bj9w",
	SCORE_MAN: "MDEwOlJlcG9zaXRvcnkyODMzNjk3NTc=",
	SIMPLE_TODO: "R_kgDOMq2Gpg",
	SOLANA_MEMORY_ISSUE: "R_kgDOKQ-nOg",
	UDDOGTA: "R_kgDOGU_rig",
	WWV_NFT_STAKING: "R_kgDOIYqZUQ"
}