import { writeFileSync } from "fs";
import { Octokit, App } from "octokit";
import "dotenv/config";
import path from "path";

function getSlug(repo: string) {
  return repo.replace(/-/g, "_");
}

function getContent(entries: Record<string, string>) {
  return `
// This file is generated by tools/generate-repo-ids.ts
// Do not edit this file directly

export const RepoIds = {
${Object.entries(entries)
  .map(([key, value]) => `\t${key}: "${value}"`)
  .join(",\n")}
}`;
}

async function main() {
  const octokit = new Octokit({
    auth: process.env.GITHUB_AUTH_TOKEN,
  });

  const { data: repos } = await octokit.rest.repos.listForAuthenticatedUser({
    type: "owner",
  });

  const ReposEntries = {} as Record<string, string>;
  repos.forEach((repo) => {
    const slug = getSlug(repo.name.toUpperCase());
    ReposEntries[slug] = repo.node_id;
  });

  writeFileSync(
    path.resolve(__dirname, "../src/utils/repo-ids.ts"),
    getContent(ReposEntries)
  );
}

main();
